Importing the necessary libraries from python

In [1]:
import pandas as pd

In [10]:
df=pd.read_csv("../Data/Raw/2009.csv")
# import os
# print(os.getcwd())
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,62.0,68.0,42.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,82.0,75.0,43.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,70.0,62.0,36.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,77.0,56.0,37.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,105.0,77.0,40.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
delay_cols = [
    'CARRIER_DELAY',
    'WEATHER_DELAY',
    'NAS_DELAY',
    'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY'
]

df[delay_cols] = df[delay_cols].fillna(0)

In [13]:
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,62.0,68.0,42.0,199.0,0.0,0.0,0.0,0.0,0.0,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,82.0,75.0,43.0,213.0,0.0,0.0,0.0,0.0,0.0,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,70.0,62.0,36.0,199.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,77.0,56.0,37.0,199.0,0.0,0.0,0.0,0.0,0.0,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,105.0,77.0,40.0,213.0,0.0,0.0,0.0,0.0,0.0,NaN

In [16]:
df.columns

Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'Unnamed: 27'],
      dtype='object')

In [18]:
df=df.drop(columns=['Unnamed: 27'])

In [19]:
df.columns

Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY'],
      dtype='object')

In [20]:
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,0.0,62.0,68.0,42.0,199.0,0.0,0.0,0.0,0.0,0.0
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,0.0,82.0,75.0,43.0,213.0,0.0,0.0,0.0,0.0,0.0
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,0.0,70.0,62.0,36.0,199.0,0.0,0.0,0.0,0.0,0.0
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,0.0,77.0,56.0,37.0,199.0,0.0,0.0,0.0,0.0,0.0
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,0.0,105.0,77.0,40.0,213.0,0.0,0.0,0.0,0.0,0.0

--DATA READINESS AND PREPROCESSING &DATA  CLEANING 
---Dataset Containg 64k+ Rows and 27 columns

In [21]:
df.shape

(6429338, 27)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6429338 entries, 0 to 6429337
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              object
 1   OP_CARRIER           object
 2   OP_CARRIER_FL_NUM    int64
 3   ORIGIN               object
 4   DEST                 object
 5   CRS_DEP_TIME         int64
 6   DEP_TIME             float64
 7   DEP_DELAY            float64
 8   TAXI_OUT             float64
 9   WHEELS_OFF           float64
 10  WHEELS_ON            float64
 11  TAXI_IN              float64
 12  CRS_ARR_TIME         int64
 13  ARR_TIME             float64
 14  ARR_DELAY            float64
 15  CANCELLED            float64
 16  CANCELLATION_CODE    object
 17  DIVERTED             float64
 18  CRS_ELAPSED_TIME     float64
 19  ACTUAL_ELAPSED_TIME  float64
 20  AIR_TIME             float64
 21  DISTANCE             float64
 22  CARRIER_DELAY        float64
 23  WEATHER_DELAY        float64
 24  NAS_DELAY            float64
 25  SECURITY_DELAY       float64
 26  LATE_AIRCRAFT_DELAY  float64
dtypes: float64(19), int64(3), object(5)
memory usage: 1.3+ GB

--CONVERTING DATATYPES 
F_DATE,CATEGORICAL DATA, NUMERICAL_BINARY COLUMN, KEEPING FLOAT FOR DELAY COLS,

In [27]:
df['FL_DATE']=pd.to_datetime(df['FL_DATE'])
df['FL_DATE'].dtype

dtype('<M8[ns]')

In [28]:
categorical_cols = [
    'OP_CARRIER',
    'ORIGIN',
    'DEST',
    'CANCELLATION_CODE'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

In [29]:
df['CANCELLED'] = df['CANCELLED'].astype('int8')
df['DIVERTED'] = df['DIVERTED'].astype('int8')

In [30]:
df['OP_CARRIER_FL_NUM'] = df['OP_CARRIER_FL_NUM'].astype('int32')

In [31]:
time_cols = [
    'CRS_DEP_TIME', 'DEP_TIME',
    'WHEELS_OFF', 'WHEELS_ON',
    'CRS_ARR_TIME', 'ARR_TIME'
]

for col in time_cols:
    df[col] = df[col].fillna(0).astype('int32')

In [32]:
delay_cols = [
    'DEP_DELAY', 'ARR_DELAY',
    'CARRIER_DELAY', 'WEATHER_DELAY',
    'NAS_DELAY', 'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY'
]

for col in delay_cols:
    df[col] = df[col].fillna(0).astype('float32')

In [33]:
df['DISTANCE'] = df['DISTANCE'].astype('int32')

elapsed_cols = ['CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME']
for col in elapsed_cols:
    df[col] = df[col].fillna(0).astype('float32')

In [34]:
# CHECKING MEMORY_USAGE
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6429338 entries, 0 to 6429337
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              datetime64[ns]
 1   OP_CARRIER           category
 2   OP_CARRIER_FL_NUM    int32
 3   ORIGIN               category
 4   DEST                 category
 5   CRS_DEP_TIME         int32
 6   DEP_TIME             int32
 7   DEP_DELAY            float32
 8   TAXI_OUT             float64
 9   WHEELS_OFF           int32
 10  WHEELS_ON            int32
 11  TAXI_IN              float64
 12  CRS_ARR_TIME         int32
 13  ARR_TIME             int32
 14  ARR_DELAY            float32
 15  CANCELLED            int8
 16  CANCELLATION_CODE    category
 17  DIVERTED             int8
 18  CRS_ELAPSED_TIME     float32
 19  ACTUAL_ELAPSED_TIME  float32
 20  AIR_TIME             float64
 21  DISTANCE             int32
 22  CARRIER_DELAY        float32
 23  WEATHER_DELAY        float32
 24  NAS_DELAY            float32
 25  SECURITY_DELAY       float32
 26  LATE_AIRCRAFT_DELAY  float32
dtypes: category(4), datetime64[ns](1), float32(9), float64(3), int32(8), int8(2)
memory usage: 662.2 MB

In [44]:
# EXPLORING SCHEMA TYPES ANS SIZE NULLS
df.isnull().sum()

FL_DATE                0
OP_CARRIER             0
OP_CARRIER_FL_NUM      0
ORIGIN                 0
DEST                   0
CRS_DEP_TIME           0
DEP_TIME               0
DEP_DELAY              0
TAXI_OUT               0
WHEELS_OFF             0
WHEELS_ON              0
TAXI_IN                0
CRS_ARR_TIME           0
ARR_TIME               0
ARR_DELAY              0
CANCELLED              0
CANCELLATION_CODE      0
DIVERTED               0
CRS_ELAPSED_TIME       0
ACTUAL_ELAPSED_TIME    0
AIR_TIME               0
DISTANCE               0
CARRIER_DELAY          0
WEATHER_DELAY          0
NAS_DELAY              0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64

In [42]:
# 1️⃣ Fix TAXI_OUT, TAXI_IN, AIR_TIME (replace null with 0)
time_cols = ['TAXI_OUT', 'TAXI_IN', 'AIR_TIME']
df[time_cols] = df[time_cols].fillna(0)

# 2️⃣ Fix CANCELLATION_CODE properly
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].astype(str)
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].replace('nan', 'Not Cancelled')
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].astype('category')

In [43]:
df[['TAXI_OUT','TAXI_IN','AIR_TIME','CANCELLATION_CODE']].isnull().sum()

TAXI_OUT             0
TAXI_IN              0
AIR_TIME             0
CANCELLATION_CODE    0
dtype: int64

In [36]:
df.describe()

,FL_DATE,OP_CARRIER_FL_NUM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
count,6429338,6.429338e+06,6.429338e+06,6.429338e+06,6.429338e+06,6.343551e+06,6.429338e+06,6.429338e+06,6.340017e+06,6.429338e+06,...,6.429338e+06,6.429338e+06,6.429338e+06,6.326977e+06,6.429338e+06,6.429338e+06,6.429338e+06,6.429338e+06,6.429338e+06,6.429338e+06
mean,2009-06-28 05:54:35.254404352,2.293712e+03,1.319447e+03,1.308935e+03,7.500247e+00,1.603613e+01,1.332774e+03,1.457966e+03,6.894225e+00,1.496722e+03,...,2.383294e-03,1.293447e+02,1.242335e+02,1.033257e+02,7.249700e+02,2.815711e+00,5.016714e-01,2.993617e+00,1.166668e-02,3.556932e+00
min,2009-01-01 00:00:00,1.000000e+00,1.000000e+00,0.000000e+00,-9.600000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,...,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2009-04-02 00:00:00,6.180000e+02,9.260000e+02,9.190000e+02,-5.000000e+00,1.000000e+01,9.340000e+02,1.057000e+03,4.000000e+00,1.119000e+03,...,0.000000e+00,8.000000e+01,7.500000e+01,5.500000e+01,3.250000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2009-06-30 00:00:00,1.629000e+03,1.315000e+03,1.316000e+03,-1.000000e+00,1.300000e+01,1.330000e+03,1.502000e+03,6.000000e+00,1.519000e+03,...,0.000000e+00,1.110000e+02,1.080000e+02,8.500000e+01,5.810000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2009-09-14 00:00:00,3.536000e+03,1.710000e+03,1.716000e+03,5.000000e+00,1.900000e+01,1.731000e+03,1.854000e+03,8.000000e+00,1.903000e+03,...,0.000000e+00,1.590000e+02,1.550000e+02,1.310000e+02,9.480000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2009-12-31 00:00:00,7.829000e+03,2.359000e+03,2.400000e+03,2.445000e+03,4.580000e+02,2.400000e+03,2.400000e+03,1.970000e+02,2.400000e+03,...,1.000000e+00,6.600000e+02,7.990000e+02,6.990000e+02,4.962000e+03,2.439000e+03,1.114000e+03,1.305000e+03,3.450000e+02,1.391000e+03
std,NaN,2.046497e+03,4.577529e+02,4.892840e+02,3.157121e+01,1.056383e+01,4.919572e+02,5.144269e+02,4.908826e+00,4.733178e+02,...,4.876078e-02,6.966364e+01,7.073971e+01,6.706977e+01,5.610229e+02,1.807461e+01,7.713589e+00,1.421012e+01,7.453483e-01,1.751772e+01

In [45]:
# SAMPLINGD
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6429338 entries, 0 to 6429337
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              datetime64[ns]
 1   OP_CARRIER           category
 2   OP_CARRIER_FL_NUM    int32
 3   ORIGIN               category
 4   DEST                 category
 5   CRS_DEP_TIME         int32
 6   DEP_TIME             int32
 7   DEP_DELAY            float32
 8   TAXI_OUT             float64
 9   WHEELS_OFF           int32
 10  WHEELS_ON            int32
 11  TAXI_IN              float64
 12  CRS_ARR_TIME         int32
 13  ARR_TIME             int32
 14  ARR_DELAY            float32
 15  CANCELLED            int8
 16  CANCELLATION_CODE    category
 17  DIVERTED             int8
 18  CRS_ELAPSED_TIME     float32
 19  ACTUAL_ELAPSED_TIME  float32
 20  AIR_TIME             float64
 21  DISTANCE             int32
 22  CARRIER_DELAY        float32
 23  WEATHER_DELAY        float32
 24  NAS_DELAY            float32
 25  SECURITY_DELAY       float32
 26  LATE_AIRCRAFT_DELAY  float32
dtypes: category(4), datetime64[ns](1), float32(9), float64(3), int32(8), int8(2)
memory usage: 662.2 MB

In [46]:
# SAMPLING 20%
df_sample=df.sample(frac=0.2,random_state=42)

FEATURE ENGINEERING AND PREPROCESSING

In [47]:
df['YEAR'] = df['FL_DATE'].dt.year
df['MONTH'] = df['FL_DATE'].dt.month
df['DAY'] = df['FL_DATE'].dt.day
df['DAY_OF_WEEK'] = df['FL_DATE'].dt.dayofweek

In [ ]:
# CREATED DEPARTURE HOUR 
df['DEP_HOUR'] = df['DEP_TIME'] // 100

In [50]:
df['ROUTE'] = df['ORIGIN'].astype(str) + "-" + df['DEST'].astype(str)

In [51]:
# season column
def get_season(month):
    if month in [12,1,2]:
        return "Winter"
    elif month in [3,4,5]:
        return "Spring"
    elif month in [6,7,8]:
        return "Summer"
    else:
        return "Fall"

df['SEASON'] = df['MONTH'].apply(get_season)
df['SEASON'] = df['SEASON'].astype('category')

In [52]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6429338 entries, 0 to 6429337
Data columns (total 34 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              datetime64[ns]
 1   OP_CARRIER           category
 2   OP_CARRIER_FL_NUM    int32
 3   ORIGIN               category
 4   DEST                 category
 5   CRS_DEP_TIME         int32
 6   DEP_TIME             int32
 7   DEP_DELAY            float32
 8   TAXI_OUT             float64
 9   WHEELS_OFF           int32
 10  WHEELS_ON            int32
 11  TAXI_IN              float64
 12  CRS_ARR_TIME         int32
 13  ARR_TIME             int32
 14  ARR_DELAY            float32
 15  CANCELLED            int8
 16  CANCELLATION_CODE    category
 17  DIVERTED             int8
 18  CRS_ELAPSED_TIME     float32
 19  ACTUAL_ELAPSED_TIME  float32
 20  AIR_TIME             float64
 21  DISTANCE             int32
 22  CARRIER_DELAY        float32
 23  WEATHER_DELAY        float32
 24  NAS_DELAY            float32
 25  SECURITY_DELAY       float32
 26  LATE_AIRCRAFT_DELAY  float32
 27  YEAR                 int32
 28  MONTH                int32
 29  DAY                  int32
 30  DAY_OF_WEEK          int32
 31  DEP_HOUR             int32
 32  ROUTE                object
 33  SEASON               category
dtypes: category(5), datetime64[ns](1), float32(9), float64(3), int32(13), int8(2), object(1)
memory usage: 840.0+ MB

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,YEAR,MONTH,DAY,DAY_OF_WEEK,DEP_HOUR,ROUTE,SEASON
0,2009-01-01,XE,1204,DCA,EWR,1100,1058,-2.0,18.0,1116,...,0.0,0.0,0.0,2009,1,1,3,10,DCA-EWR,Winter
1,2009-01-01,XE,1206,EWR,IAD,1510,1509,-1.0,28.0,1537,...,0.0,0.0,0.0,2009,1,1,3,15,EWR-IAD,Winter
2,2009-01-01,XE,1207,EWR,DCA,1100,1059,-1.0,20.0,1119,...,0.0,0.0,0.0,2009,1,1,3,10,EWR-DCA,Winter
3,2009-01-01,XE,1208,DCA,EWR,1240,1249,9.0,10.0,1259,...,0.0,0.0,0.0,2009,1,1,3,12,DCA-EWR,Winter
4,2009-01-01,XE,1209,IAD,EWR,1715,1705,-10.0,24.0,1729,...,0.0,0.0,0.0,2009,1,1,3,17,IAD-EWR,Winter

In [53]:
df.to_csv("../Data/Processed/flights_2009_processed.csv", index=False)

Week 3 – Univariate & Bivariate Visual Analysis