In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\prakash\OneDrive\Desktop\Air fly\Airline Dataset Updated - v2.csv")

df.head()

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  str
 1   First Name            98619 non-null  str
 2   Last Name             98619 non-null  str
 3   Gender                98619 non-null  str
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  str
 6   Airport Name          98619 non-null  str
 7   Airport Country Code  98619 non-null  str
 8   Country Name          98619 non-null  str
 9   Airport Continent     98619 non-null  str
 10  Continents            98619 non-null  str
 11  Departure Date        98619 non-null  str
 12  Arrival Airport       98619 non-null  str
 13  Pilot Name            98619 non-null  str
 14  Flight Status         98619 non-null  str
dtypes: int64(1), str(14)
memory usage: 21.7 MB

In [4]:
df.shape

(98619, 15)

In [5]:
df.isnull().sum()

Passenger ID            0
First Name              0
Last Name               0
Gender                  0
Age                     0
Nationality             0
Airport Name            0
Airport Country Code    0
Country Name            0
Airport Continent       0
Continents              0
Departure Date          0
Arrival Airport         0
Pilot Name              0
Flight Status           0
dtype: int64

In [6]:
df.describe()

                Age
count  98619.000000
mean      45.504021
std       25.929849
min        1.000000
25%       23.000000
50%       46.000000
75%       68.000000
max       90.000000

In [7]:
df = df.drop_duplicates()

In [8]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\prakash\AppData\Local\Temp\ipykernel_26828\1698716155.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

0        62
1        62
2        67
3        71
4        21
         ..
98614    85
98615    19
98616    65
98617    34
98618    10
Name: Age, Length: 98619, dtype: int64

In [9]:

df['Nationality'].fillna(df['Nationality'].mode()[0], inplace=True)

C:\Users\prakash\AppData\Local\Temp\ipykernel_26828\3398413860.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Nationality'].fillna(df['Nationality'].mode()[0], inplace=True)

0            Japan
1        Nicaragua
2           Russia
3            China
4            China
           ...
98614        China
98615       Russia
98616    Indonesia
98617        China
98618       Poland
Name: Nationality, Length: 98619, dtype: str

In [10]:
df['Airport Name'].fillna(df['Airport Name'].mode()[0], inplace=True)

C:\Users\prakash\AppData\Local\Temp\ipykernel_26828\1900207956.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Airport Name'].fillna(df['Airport Name'].mode()[0], inplace=True)

0                   Coldfoot Airport
1                  Kugluktuk Airport
2             Grenoble-Isère Airport
3          Ottawa / Gatineau Airport
4                    Gillespie Field
                    ...
98614                 Hasvik Airport
98615            Ampampamena Airport
98616    Albacete-Los Llanos Airport
98617                 Gagnoa Airport
98618            Yoshkar-Ola Airport
Name: Airport Name, Length: 98619, dtype: str

In [11]:
df['Departure Date'] = pd.to_datetime(df['Departure Date'], format='mixed')

In [12]:
df['Month'] = df['Departure Date'].dt.month

In [13]:
df['Departure Date'] = pd.to_datetime(df['Departure Date'], format='mixed', errors='coerce')

In [14]:
df['Day'] = df['Departure Date'].dt.day

In [15]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\prakash\AppData\Local\Temp\ipykernel_26828\1698716155.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

0        62
1        62
2        67
3        71
4        21
         ..
98614    85
98615    19
98616    65
98617    34
98618    10
Name: Age, Length: 98619, dtype: int64

In [16]:
df['day_of_week'] = df['Departure Date'].dt.dayofweek

In [17]:
df.to_csv("cleaned_dataset.csv", index=False)