Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os


Check Working Directory

In [2]:
print(os.getcwd())

c:\Users\Ankita\airfly_insights_dashboard\notebooks

Load Dataset

In [3]:
file_path = "../data/raw/Airline Dataset Updated - v2.csv"
df = pd.read_csv(file_path)

print("Dataset Loaded Successfully ✅")
print("Shape:", df.shape)

Dataset Loaded Successfully ✅
Shape: (98619, 15)

Basic Data Understanding

In [4]:
df.head()

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  object
 1   First Name            98619 non-null  object
 2   Last Name             98619 non-null  object
 3   Gender                98619 non-null  object
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  object
 6   Airport Name          98619 non-null  object
 7   Airport Country Code  98619 non-null  object
 8   Country Name          98619 non-null  object
 9   Airport Continent     98619 non-null  object
 10  Continents            98619 non-null  object
 11  Departure Date        98619 non-null  object
 12  Arrival Airport       98619 non-null  object
 13  Pilot Name            98619 non-null  object
 14  Flight Status         98619 non-null  object
dtypes: int64(1), object(14)
memory usage: 11.3+ MB

In [6]:
df.describe()

                Age
count  98619.000000
mean      45.504021
std       25.929849
min        1.000000
25%       23.000000
50%       46.000000
75%       68.000000
max       90.000000

Check Missing Values

In [7]:
df.isnull().sum()

Passenger ID            0
First Name              0
Last Name               0
Gender                  0
Age                     0
Nationality             0
Airport Name            0
Airport Country Code    0
Country Name            0
Airport Continent       0
Continents              0
Departure Date          0
Arrival Airport         0
Pilot Name              0
Flight Status           0
dtype: int64

Handle Missing Values

In [8]:
print("No missing values found ✅")

No missing values found ✅

 Convert Departure Date to datetime

In [9]:
print(df['Departure Date'].head())
print(df['Departure Date'].dtype)

0     6/28/2022
1    12/26/2022
2     1/18/2022
3     9/16/2022
4     2/25/2022
Name: Departure Date, dtype: object
object

In [10]:
df['Departure Date'] = pd.to_datetime(
    df['Departure Date'],
    errors='coerce',
    infer_datetime_format=True
)

C:\Users\Ankita\AppData\Local\Temp\ipykernel_3024\975580133.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['Departure Date'] = pd.to_datetime(

In [11]:
df['Departure Date'].isnull().sum()

np.int64(38961)

Feature Engineering

In [12]:
df['Year'] = df['Departure Date'].dt.year
df['Month'] = df['Departure Date'].dt.month
df['Day'] = df['Departure Date'].dt.day
df['DayOfWeek'] = df['Departure Date'].dt.day_name()

In [13]:
df.head()

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Year,Month,Day,DayOfWeek
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,2022-06-28,CXF,Fransisco Hazeldine,On Time,2022.0,6.0,28.0,Tuesday
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,2022-12-26,YCO,Marla Parsonage,On Time,2022.0,12.0,26.0,Monday
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,2022-01-18,GNB,Rhonda Amber,On Time,2022.0,1.0,18.0,Tuesday
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,2022-09-16,YND,Kacie Commucci,Delayed,2022.0,9.0,16.0,Friday
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2022-02-25,SEE,Ebonee Tree,On Time,2022.0,2.0,25.0,Friday

Convert Categorical Columns (Memory Optimization)

In [14]:
categorical_cols = [
    'Gender',
    'Nationality',
    'Airport Name',
    'Country Name',
    'Airport Continent',
    'Arrival Airport',
    'Flight Status'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

Final Dataset Check

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  object
 1   First Name            98619 non-null  object
 2   Last Name             98619 non-null  object
 3   Gender                98619 non-null  category
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  category
 6   Airport Name          98619 non-null  category
 7   Airport Country Code  98619 non-null  object
 8   Country Name          98619 non-null  category
 9   Airport Continent     98619 non-null  category
 10  Continents            98619 non-null  object
 11  Departure Date        59658 non-null  datetime64[ns]
 12  Arrival Airport       98619 non-null  category
 13  Pilot Name            98619 non-null  object
 14  Flight Status         98619 non-null  category
 15  Year                  59658 non-null  float64
 16  Month                 59658 non-null  float64
 17  Day                   59658 non-null  float64
 18  DayOfWeek             59658 non-null  object
dtypes: category(7), datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 10.7+ MB

Save Cleaned Dataset

In [16]:
df.to_csv("../data/processed/cleaned_airline_data.csv", index=False)
print("Milestone 1 Completed ✅")

Milestone 1 Completed ✅