Loading the raw data set

In [1]:
import pandas as pd 
df = pd.read_csv("../data/raw/flights.csv")
df.head()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,name
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.

Checking the memory usage before optimization

In [2]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int64
 2   month           336776 non-null  int64
 3   day             336776 non-null  int64
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float64
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float64
 10  carrier         336776 non-null  object
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  object
 13  origin          336776 non-null  object
 14  dest            336776 non-null  object
 15  air_time        327346 non-null  float64
 16  distance        336776 non-null  int64
 17  hour            336776 non-null  int64
 18  minute          336776 non-null  int64
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  object
dtypes: float64(5), int64(10), object(6)
memory usage: 149.6 MB

Optimization

Converting to category

In [3]:
categorical_cols = ['carrier', 'origin', 'dest', 'tailnum', 'name']
for col in categorical_cols:
    df[col] = df[col].astype('category')

Downcasting integer columns

In [4]:
df['year'] = df['year'].astype('int16')
df['month'] = df['month'].astype('int8')
df['day'] =  df['day'].astype('int8')
df['hour'] = df['hour'].astype('int8')
df['minute'] = df['minute'].astype('int8')
df['distance'] = df['distance'].astype('int16')

Downcasting floats

In [5]:
df['dep_delay'] = pd.to_numeric(df['dep_delay'], downcast='float')
df['arr_delay'] = pd.to_numeric(df['arr_delay'], downcast='float')
df['air_time'] = pd.to_numeric(df['air_time'], downcast='float')

Checking memory usage after optimization

In [6]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int16
 2   month           336776 non-null  int8
 3   day             336776 non-null  int8
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float32
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float32
 10  carrier         336776 non-null  category
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  category
 13  origin          336776 non-null  category
 14  dest            336776 non-null  category
 15  air_time        327346 non-null  float32
 16  distance        336776 non-null  int16
 17  hour            336776 non-null  int8
 18  minute          336776 non-null  int8
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  category
dtypes: category(5), float32(3), float64(2), int16(2), int64(4), int8(4), object(1)
memory usage: 46.0 MB

### Before  

###### dtypes: float64(5), int64(10), object(6)

###### memory usage: 149.6 MB

### After 

###### dtypes: category(5), float32(3), float64(2), int16(2), int64(4), int8(4), object(1)

###### memory usage: 46.0 MB

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int16
 2   month           336776 non-null  int8
 3   day             336776 non-null  int8
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float32
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float32
 10  carrier         336776 non-null  category
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  category
 13  origin          336776 non-null  category
 14  dest            336776 non-null  category
 15  air_time        327346 non-null  float32
 16  distance        336776 non-null  int16
 17  hour            336776 non-null  int8
 18  minute          336776 non-null  int8
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  category
dtypes: category(5), float32(3), float64(2), int16(2), int64(4), int8(4), object(1)
memory usage: 26.5+ MB

### Cancelled Flag

##### 1 → Cancelled flight
##### 0 → Completed flight

In [8]:
df['cancelled'] = df['dep_time'].isna().astype(int)

### Creating proper date column

In [9]:
df['flight_date'] = pd.to_datetime(df[['year', 'month', 'day']])

### Day of week

In [10]:
df['day_of_week'] = df['flight_date'].dt.day_name()

### Route column

In [11]:
df['route'] = df['origin'].astype(str) + "-" + df['dest'].astype(str)

### On-Time indicator

In [12]:
df['on_time'] = (df['arr_delay'] <= 0).astype(int)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 26 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int16
 2   month           336776 non-null  int8
 3   day             336776 non-null  int8
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float32
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float32
 10  carrier         336776 non-null  category
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  category
 13  origin          336776 non-null  category
 14  dest            336776 non-null  category
 15  air_time        327346 non-null  float32
 16  distance        336776 non-null  int16
 17  hour            336776 non-null  int8
 18  minute          336776 non-null  int8
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  category
 21  cancelled       336776 non-null  int64
 22  flight_date     336776 non-null  datetime64[ns]
 23  day_of_week     336776 non-null  object
 24  route           336776 non-null  object
 25  on_time         336776 non-null  int64
dtypes: category(5), datetime64[ns](1), float32(3), float64(2), int16(2), int64(6), int8(4), object(3)
memory usage: 39.3+ MB

In [14]:
df.columns

Index(['id', 'year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour', 'name', 'cancelled', 'flight_date', 'day_of_week', 'route',
       'on_time'],
      dtype='object')

In [15]:
df.dtypes

id                         int64
year                       int16
month                       int8
day                         int8
dep_time                 float64
sched_dep_time             int64
dep_delay                float32
arr_time                 float64
sched_arr_time             int64
arr_delay                float32
carrier                 category
flight                     int64
tailnum                 category
origin                  category
dest                    category
air_time                 float32
distance                   int16
hour                        int8
minute                      int8
time_hour                 object
name                    category
cancelled                  int64
flight_date       datetime64[ns]
day_of_week               object
route                     object
on_time                    int64
dtype: object

### Checking Missing Values for Cancelled Flights

In [16]:
df[df['cancelled'] == 1][['dep_time','arr_delay']].head()

      dep_time  arr_delay
838        NaN        NaN
839        NaN        NaN
840        NaN        NaN
841        NaN        NaN
1777       NaN        NaN

### Checking On-Time Flag Against Arrival Delay

In [17]:
df[['arr_delay','on_time']].sample(10)

        arr_delay  on_time
72532       -18.0        1
246344      -14.0        1
195112       -1.0        1
113681       38.0        0
232061       62.0        0
122750        2.0        0
213545      -10.0        1
266175      232.0        0
190215      -38.0        1
30195       -20.0        1

### Checking for Non-Cancelled Flights with Missing arr_delay

In [18]:
df[(df['cancelled'] == 0) & (df['arr_delay'].isna())]

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,distance,hour,minute,time_hour,name,cancelled,flight_date,day_of_week,route,on_time
471,471,2013,1,1,1525.0,1530,-5.0,1934.0,1805,NaN,...,1147,15,30,2013-01-01 15:00:00,Envoy Air,0,2013-01-01,Tuesday,LGA-XNA,0
477,477,2013,1,1,1528.0,1459,29.0,2002.0,1647,NaN,...,872,14,59,2013-01-01 14:00:00,ExpressJet Airlines Inc.,0,2013-01-01,Tuesday,EWR-STL,0
615,615,2013,1,1,1740.0,1745,-5.0,2158.0,2020,NaN,...,1147,17,45,2013-01-01 17:00:00,Envoy Air,0,2013-01-01,Tuesday,LGA-XNA,0
643,643,2013,1,1,1807.0,1738,29.0,2251.0,2103,NaN,...,2425,17,38,2013-01-01 17:00:00,United Air Lines Inc.,0,2013-01-01,Tuesday,EWR-SAN,0
725,725,2013,1,1,1939.0,1840,59.0,29.0,2151,NaN,...,1391,18,40,2013-01-01 18:00:00,Endeavor Air Inc.,0,2013-01-01,Tuesday,JFK-DFW,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334354,334354,2013,9,28,847.0,839,8.0,1130.0,959,NaN,...,725,8,39,2013-09-28 08:00:00,ExpressJet Airlines Inc.,0,2013-09-28,Saturday,EWR-MKE,0
334412,334412,2013,9,28,1010.0,1020,-10.0,1344.0,1222,NaN,...,1017,10,20,2013-09-28 10:00:00,ExpressJet Airlines Inc.,0,2013-09-28,Saturday,EWR-DSM,0
334495,334495,2013,9,28,1214.0,1225,-11.0,1801.0,1510,NaN,...,1372,12,25,2013-09-28 12:00:00,American Airlines Inc.,0,2013-09-28,Saturday,EWR-DFW,0
335534,335534,2013,9,29,1734.0,1711,23.0,2159.0,2020,NaN,...,2434,17,11,2013-09-29 17:00:00,United Air Lines Inc.,0,2013-09-29,Sunday,EWR-PDX,0
335805,335805,2013,9,30,559.0,600,-1.0,NaN,715,NaN,...,711,6,0,2013-09-30 06:00:00,Southwest Airlines Co.,0,2013-09-30,Monday,EWR-MDW,0

In [19]:
df.shape

(336776, 26)

### Verifying That There Are No Missing Values in arr_delay

In [20]:
df['arr_delay'].isna().sum()

np.int64(9430)

In [21]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 26 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int16
 2   month           336776 non-null  int8
 3   day             336776 non-null  int8
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float32
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float32
 10  carrier         336776 non-null  category
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  category
 13  origin          336776 non-null  category
 14  dest            336776 non-null  category
 15  air_time        327346 non-null  float32
 16  distance        336776 non-null  int16
 17  hour            336776 non-null  int8
 18  minute          336776 non-null  int8
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  category
 21  cancelled       336776 non-null  int64
 22  flight_date     336776 non-null  datetime64[ns]
 23  day_of_week     336776 non-null  object
 24  route           336776 non-null  object
 25  on_time         336776 non-null  int64
dtypes: category(5), datetime64[ns](1), float32(3), float64(2), int16(2), int64(6), int8(4), object(3)
memory usage: 89.7 MB

In [22]:
df['cancelled'].value_counts()

cancelled
0    328521
1      8255
Name: count, dtype: int64