In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/flights.csv")

df.head()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,name
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.

In [2]:
df.shape

(336776, 21)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int64
 2   month           336776 non-null  int64
 3   day             336776 non-null  int64
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float64
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float64
 10  carrier         336776 non-null  object
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  object
 13  origin          336776 non-null  object
 14  dest            336776 non-null  object
 15  air_time        327346 non-null  float64
 16  distance        336776 non-null  int64
 17  hour            336776 non-null  int64
 18  minute          336776 non-null  int64
 19  time_hour       336776 non-null  object
 20  name            336776 non-null  object
dtypes: float64(5), int64(10), object(6)
memory usage: 54.0+ MB

In [4]:
df.isnull().sum()

id                   0
year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
name                 0
dtype: int64

In [11]:
df_sample = df.sample(100000, random_state=42)
df_sample.shape

(100000, 23)

In [13]:
categorical_cols = ['carrier', 'origin', 'dest', 'name']

for col in categorical_cols:
    df[col] = df[col].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               336776 non-null  int64
 1   year             336776 non-null  int64
 2   month            336776 non-null  int64
 3   day              336776 non-null  int64
 4   dep_time         328521 non-null  float64
 5   sched_dep_time   336776 non-null  int64
 6   dep_delay        328521 non-null  float64
 7   arr_time         328063 non-null  float64
 8   sched_arr_time   336776 non-null  int64
 9   arr_delay        327346 non-null  float64
 10  carrier          336776 non-null  category
 11  flight           336776 non-null  int64
 12  tailnum          334264 non-null  object
 13  origin           336776 non-null  category
 14  dest             336776 non-null  category
 15  air_time         327346 non-null  float64
 16  distance         336776 non-null  int64
 17  hour             336776 non-null  int64
 18  minute           336776 non-null  int64
 19  time_hour        336776 non-null  object
 20  name             336776 non-null  category
 21  is_cancelled     336776 non-null  bool
 22  arrival_missing  336776 non-null  bool
dtypes: bool(2), category(4), float64(5), int64(10), object(2)
memory usage: 45.6+ MB

In [14]:
df[['dep_delay','arr_delay']].isnull().sum()

dep_delay    8255
arr_delay    9430
dtype: int64

In [17]:
df['is_cancelled'] = df['dep_time'].isnull()

In [18]:
df['date'] = pd.to_datetime(df[['year','month','day']])

In [19]:
df['month_name'] = df['date'].dt.month_name()

In [20]:
df['day_of_week'] = df['date'].dt.day_name()

In [26]:
df['hour'] = df['sched_dep_time'] // 100
df.head()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,hour,minute,time_hour,name,is_cancelled,arrival_missing,date,month_name,day_of_week,route
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,5,15,2013-01-01 05:00:00,United Air Lines Inc.,False,False,2013-01-01,January,Tuesday,EWR-IAH
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,5,29,2013-01-01 05:00:00,United Air Lines Inc.,False,False,2013-01-01,January,Tuesday,LGA-IAH
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,5,40,2013-01-01 05:00:00,American Airlines Inc.,False,False,2013-01-01,January,Tuesday,JFK-MIA
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,5,45,2013-01-01 05:00:00,JetBlue Airways,False,False,2013-01-01,January,Tuesday,JFK-BQN
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.,False,False,2013-01-01,January,Tuesday,LGA-ATL

In [ ]:
df['route'] = df['origin'].astype(str) + "-" + df['dest'].astype(str)
df.head()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,hour,minute,time_hour,name,is_cancelled,arrival_missing,date,month_name,day_of_week,route
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,5,15,2013-01-01 05:00:00,United Air Lines Inc.,False,False,2013-01-01,January,Tuesday,EWR-IAH
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,5,29,2013-01-01 05:00:00,United Air Lines Inc.,False,False,2013-01-01,January,Tuesday,LGA-IAH
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,5,40,2013-01-01 05:00:00,American Airlines Inc.,False,False,2013-01-01,January,Tuesday,JFK-MIA
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,5,45,2013-01-01 05:00:00,JetBlue Airways,False,False,2013-01-01,January,Tuesday,JFK-BQN
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.,False,False,2013-01-01,January,Tuesday,LGA-ATL

In [24]:
df[['origin','dest','route']].head()

  origin dest    route
0    EWR  IAH  EWR-IAH
1    LGA  IAH  LGA-IAH
2    JFK  MIA  JFK-MIA
3    JFK  BQN  JFK-BQN
4    LGA  ATL  LGA-ATL

In [27]:
df['is_delayed'] = df['dep_delay'] > 15

In [28]:
df['is_weekend'] = df['day_of_week'].isin(['Saturday','Sunday'])
#weekend flag to analyze delay differences between weekdays and weekends.

In [29]:
df.duplicated().sum()

0

In [30]:
df.to_csv("../data/flights_cleaned_m1.csv", index=False)