Completed Milestone 1 tasks:

Week 1:
- Loaded dataset sample (200,000 rows)
- Explored dataset structure
- Checked data types and null values

Week 2:
- Removed unnecessary index column
- Checked and handled duplicates
- Created new feature: route
- Converted categorical columns
- Validated numeric columns
- Optimized memory usage

Dataset is now clean and ready for visual analysis.

In [ ]:
import pandas as pd

df = pd.read_csv("../data/flights.csv", nrows=200000)

df.head()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [7]:
df.drop(columns=['index'], inplace=True)
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [8]:
df.duplicated().sum()

0

In [9]:
df['route'] = df['source_city'] + " → " + df['destination_city']
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,route
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,Delhi → Mumbai
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,Delhi → Mumbai
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,Delhi → Mumbai
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,Delhi → Mumbai
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Delhi → Mumbai

In [10]:
categorical_cols = [
    'airline',
    'flight',
    'source_city',
    'departure_time',
    'stops',
    'arrival_time',
    'destination_city',
    'class',
    'route'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           200000 non-null  category
 1   flight            200000 non-null  category
 2   source_city       200000 non-null  category
 3   departure_time    200000 non-null  category
 4   stops             200000 non-null  category
 5   arrival_time      200000 non-null  category
 6   destination_city  200000 non-null  category
 7   class             200000 non-null  category
 8   duration          200000 non-null  float64
 9   days_left         200000 non-null  int64
 10  price             200000 non-null  int64
 11  route             200000 non-null  category
dtypes: category(9), float64(1), int64(2)
memory usage: 6.5 MB

In [12]:
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')

In [13]:
df.isnull().sum()

airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
route               0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           200000 non-null  category
 1   flight            200000 non-null  category
 2   source_city       200000 non-null  category
 3   departure_time    200000 non-null  category
 4   stops             200000 non-null  category
 5   arrival_time      200000 non-null  category
 6   destination_city  200000 non-null  category
 7   class             200000 non-null  category
 8   duration          200000 non-null  float64
 9   days_left         200000 non-null  int64
 10  price             200000 non-null  int64
 11  route             200000 non-null  category
dtypes: category(9), float64(1), int64(2)
memory usage: 6.5 MB

In [15]:
df.to_csv("../data/flights_cleaned.csv", index=False)